import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import Providers from "@/app/ui/providers/Providers";
import "./globals.css";
import App from "@/app/ui/App";
import {InitColorSchemeScript} from "@mui/material";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable} suppressHydrationWarning>
      <body>
        <InitColorSchemeScript />
          <Providers>
              <App>
                {children}
              </App>
          </Providers>
      </body>
    </html>
  );
}
